const errors = {
    HTTP_CODE_BAD_REQUEST: 400,
    HTTP_STATUS_BAD_REQUEST: 'bad request',
    HTTP_CODE_UNAUTHORIZED: 401,
    HTTP_STATUS_UNAUTHORIZED: 'unauthorized',
    HTTP_CODE_FORBIDDEN: 403,
    HTTP_STATUS_FORBIDDEN: 'forbidden',
    HTTP_CODE_NOT_FOUND: 404,
    HTTP_STATUS_NOT_FOUND: 'not found',
    HTTP_CODE_INTERNAL_SERVER_ERROR: 500,
    HTTP_STATUS_INTERNAL_SERVER_ERROR: 'internal server error',
    ERROR_AUTHORIZATION: 'you are not authorized',
    ERROR_FORBIDDEN: 'you are not allowed to access this resource',
    ERROR_USER_NOT_FOUND: 'user is not found',
    ERROR_SERVER_ERROR: 'server Error',
    ERROR_WRONG_AUTHENTICATION: 'username or password is wrong',
    ERROR_USER_ALREADY_EXISTS: 'user already exists',
    ERROR_ROLE_REQUIRED: 'role is required',
    ERROR_ROLE_NUMBER: 'role must be a number',
    ERROR_ROLE_POSITIVE: 'role must be a positive number',
    ERROR_FULL_NAME_STRING: 'full name must be a string',
    ERROR_FULL_NAME_EMPTY: 'full name cannot be empty',
    ERROR_FULL_NAME_MIN: 'min 3 characters',
    ERROR_FULL_NAME_MAX: 'max 255 characters',
    ERROR_FULL_NAME_REQUIRED: 'full name is required',
    ERROR_USERNAME_STRING: 'username must be a string',
    ERROR_USERNAME_EMPTY: 'username cannot be empty',
    ERROR_USERNAME_MIN: 'min 3 characters',
    ERROR_USERNAME_MAX: 'max 30 characters',
    ERROR_USERNAME_REQUIRED: 'username is required',
    ERROR_EMAIL_STRING: 'email must be a string',
    ERROR_EMAIL_EMPTY: 'email cannot be empty',
    ERROR_EMAIL_INVALID: 'email must be a valid email',
    ERROR_EMAIL_REQUIRED: 'email is required',
    ERROR_USERID_NUMBER: 'user id must be a number',
    ERROR_USERID_POSITIVE: 'user id must be a positive number',
    ERROR_USERID_REQUIRED: 'user id is required',
    ERROR_PASSWORD_STRING: 'password must be a string',
    ERROR_PASSWORD_EMPTY: 'password cannot be empty',
    ERROR_PASSWORD_MIN: 'min 6 characters',
    ERROR_PASSWORD_MAX: 'max 255 characters',
    ERROR_PASSWORD_REQUIRED: 'password is required',
    ERROR_PASSWORD_PATTERN: 'password must be a valid password',
    ERROR_FAILED_TO_ADD_USER: 'failed to add user',
    ERROR_ROLE_STRING: 'role must be a string',
    ERROR_ROLE_MAX: 'max 30 characters',
}

export { errors }
